const LOT_DATA = {
  "imageWidthFt": 141.79,
  "imagePxWidth": 1162,
  "imagePxHeight": 837,
  "plants": [
    {
      "id": 1,
      "category": "Trees",
      "genus": "Serviceberry",
      "cultivar": "Standing Ovation",
      "displayName": "Serviceberry 'Standing Ovation'",
      "height": "12\u201315 ft",
      "width": "3\u20134 ft",
      "heightFt": 13.5,
      "widthFt": 3.5,
      "color": "White flowers, red/dark berries",
      "bloomTime": "Spring",
      "spacing": "4\u20136 ft"
    },
    {
      "id": 2,
      "category": "Trees",
      "genus": "Serviceberry",
      "cultivar": "Rainbow Pillar",
      "displayName": "Serviceberry 'Rainbow Pillar'",
      "height": "15\u201320 ft",
      "width": "8\u201310 ft",
      "heightFt": 17.5,
      "widthFt": 9.0,
      "color": "White flowers, dark purple berries",
      "bloomTime": "Spring",
      "spacing": "8\u201310 ft"
    },
    {
      "id": 3,
      "category": "Trees",
      "genus": "Serviceberry",
      "cultivar": "Autumn Brilliance",
      "displayName": "Serviceberry 'Autumn Brilliance'",
      "height": "20\u201325 ft",
      "width": "15\u201320 ft",
      "heightFt": 22.5,
      "widthFt": 17.5,
      "color": "White flowers, orange-red fall foliage",
      "bloomTime": "Spring",
      "spacing": "15\u201320 ft"
    },
    {
      "id": 4,
      "category": "Trees",
      "genus": "Eastern redbud",
      "cultivar": "Appalachian Red",
      "displayName": "Eastern redbud 'Appalachian Red'",
      "height": "15\u201325 ft",
      "width": "15\u201325 ft",
      "heightFt": 20.0,
      "widthFt": 20.0,
      "color": "Fuchsia/bright pink-red flowers",
      "bloomTime": "Early Spring",
      "spacing": "15\u201320 ft"
    },
    {
      "id": 5,
      "category": "Trees",
      "genus": "Eastern redbud",
      "cultivar": "Black Pearl",
      "displayName": "Eastern redbud 'Black Pearl'",
      "height": "15\u201320 ft",
      "width": "15\u201320 ft",
      "heightFt": 17.5,
      "widthFt": 17.5,
      "color": "Lavender-pink, dark purple/black foliage",
      "bloomTime": "Early Spring",
      "spacing": "15\u201320 ft"
    },
    {
      "id": 6,
      "category": "Trees",
      "genus": "Japanese tree lilac",
      "cultivar": "Ivory Silk",
      "displayName": "Japanese tree lilac 'Ivory Silk'",
      "height": "20\u201325 ft",
      "width": "15\u201320 ft",
      "heightFt": 22.5,
      "widthFt": 17.5,
      "color": "Creamy white fragrant flowers",
      "bloomTime": "Early Summer (June)",
      "spacing": "15\u201320 ft"
    },
    {
      "id": 7,
      "category": "Trees",
      "genus": "White oak",
      "cultivar": "Straight species",
      "displayName": "White oak 'Straight species'",
      "height": "50\u201380 ft",
      "width": "50\u201380 ft",
      "heightFt": 65.0,
      "widthFt": 65.0,
      "color": "Inconspicuous blooms, red/wine fall color",
      "bloomTime": "Spring",
      "spacing": "30\u201340 ft"
    },
    {
      "id": 8,
      "category": "Trees",
      "genus": "Red oak",
      "cultivar": "Straight species",
      "displayName": "Red oak 'Straight species'",
      "height": "60\u201375 ft",
      "width": "45\u201350 ft",
      "heightFt": 67.5,
      "widthFt": 47.5,
      "color": "Inconspicuous blooms, bright red fall foliage",
      "bloomTime": "Spring",
      "spacing": "30\u201340 ft"
    },
    {
      "id": 9,
      "category": "Trees",
      "genus": "Red maple",
      "cultivar": "Red Sunset",
      "displayName": "Red maple 'Red Sunset'",
      "height": "45\u201350 ft",
      "width": "35\u201340 ft",
      "heightFt": 47.5,
      "widthFt": 37.5,
      "color": "Red flowers, brilliant red fall foliage",
      "bloomTime": "Early Spring",
      "spacing": "25\u201330 ft"
    },
    {
      "id": 10,
      "category": "Trees",
      "genus": "Red maple",
      "cultivar": "October Glory",
      "displayName": "Red maple 'October Glory'",
      "height": "40\u201350 ft",
      "width": "30\u201340 ft",
      "heightFt": 45.0,
      "widthFt": 35.0,
      "color": "Red flowers, deep crimson fall foliage",
      "bloomTime": "Early Spring",
      "spacing": "25\u201330 ft"
    },
    {
      "id": 11,
      "category": "Trees",
      "genus": "Red maple",
      "cultivar": "Redpointe",
      "displayName": "Red maple 'Redpointe'",
      "height": "40\u201345 ft",
      "width": "25\u201330 ft",
      "heightFt": 42.5,
      "widthFt": 27.5,
      "color": "Red flowers, bright red fall color",
      "bloomTime": "Early Spring",
      "spacing": "20\u201325 ft"
    },
    {
      "id": 12,
      "category": "Trees",
      "genus": "Tulip tree",
      "cultivar": "Liriodendron tulipifera",
      "displayName": "Tulip tree 'Liriodendron tulipifera'",
      "height": "70\u201390 ft",
      "width": "35\u201350 ft",
      "heightFt": 80.0,
      "widthFt": 42.5,
      "color": "Tulip-shaped yellow-green & orange flowers",
      "bloomTime": "Late Spring",
      "spacing": "35\u201340 ft"
    },
    {
      "id": 13,
      "category": "Trees",
      "genus": "River birch",
      "cultivar": "Heritage",
      "displayName": "River birch 'Heritage'",
      "height": "40\u201350 ft",
      "width": "30\u201340 ft",
      "heightFt": 45.0,
      "widthFt": 35.0,
      "color": "Exfoliating creamy salmon bark",
      "bloomTime": "Spring",
      "spacing": "25\u201330 ft"
    },
    {
      "id": 14,
      "category": "Trees",
      "genus": "Eastern white pine",
      "cultivar": "Golden Candles",
      "displayName": "Eastern white pine 'Golden Candles'",
      "height": "20\u201330 ft",
      "width": "10\u201315 ft",
      "heightFt": 25.0,
      "widthFt": 12.5,
      "color": "Golden yellow needle tips, evergreen",
      "bloomTime": "Year-round",
      "spacing": "12\u201315 ft"
    },
    {
      "id": 15,
      "category": "Trees",
      "genus": "Eastern white pine",
      "cultivar": "Stowe's Pillar",
      "displayName": "Eastern white pine 'Stowe's Pillar'",
      "height": "8\u201310 ft",
      "width": "2\u20133 ft",
      "heightFt": 9.0,
      "widthFt": 2.5,
      "color": "Blue-green needles, columnar foliage",
      "bloomTime": "Year-round",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 16,
      "category": "Trees",
      "genus": "Eastern white pine",
      "cultivar": "Mini Twists",
      "displayName": "Eastern white pine 'Mini Twists'",
      "height": "4\u20136 ft",
      "width": "3\u20134 ft",
      "heightFt": 5.0,
      "widthFt": 3.5,
      "color": "Twisted blue-green needles",
      "bloomTime": "Year-round",
      "spacing": "4\u20135 ft"
    },
    {
      "id": 17,
      "category": "Trees",
      "genus": "Eastern red cedar",
      "cultivar": "Straight species",
      "displayName": "Eastern red cedar 'Straight species'",
      "height": "30\u201340 ft",
      "width": "8\u201315 ft",
      "heightFt": 35.0,
      "widthFt": 11.5,
      "color": "Dark green/bronze evergreen, blue cones",
      "bloomTime": "Year-round",
      "spacing": "10\u201315 ft"
    },
    {
      "id": 18,
      "category": "Trees",
      "genus": "Spruce",
      "cultivar": "Serbian spruce 'Nana'",
      "displayName": "Spruce 'Serbian spruce 'Nana''",
      "height": "8\u201310 ft",
      "width": "8\u201310 ft",
      "heightFt": 9.0,
      "widthFt": 9.0,
      "color": "Blue-green and silver needles, dwarf cone",
      "bloomTime": "Year-round",
      "spacing": "8\u201310 ft"
    },
    {
      "id": 19,
      "category": "Trees",
      "genus": "Mugo Pine",
      "cultivar": "Green Candle",
      "displayName": "Mugo Pine 'Green Candle'",
      "height": "3\u20135 ft",
      "width": "3\u20134 ft",
      "heightFt": 4.0,
      "widthFt": 3.5,
      "color": "Rich green needles with showy white candles",
      "bloomTime": "Year-round",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 20,
      "category": "Trees",
      "genus": "Mugo Pine",
      "cultivar": "Blue Shag",
      "displayName": "Mugo Pine 'Blue Shag'",
      "height": "2\u20134 ft",
      "width": "2\u20134 ft",
      "heightFt": 3.0,
      "widthFt": 3.0,
      "color": "Soft blue-green needles, mounding",
      "bloomTime": "Year-round",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 21,
      "category": "Trees",
      "genus": "Mugo Pine",
      "cultivar": "Jakobsen",
      "displayName": "Mugo Pine 'Jakobsen'",
      "height": "1\u20132 ft",
      "width": "2\u20133 ft",
      "heightFt": 1.5,
      "widthFt": 2.5,
      "color": "Dark green needles, bonsai-like habit",
      "bloomTime": "Year-round",
      "spacing": "2\u20133 ft"
    },
    {
      "id": 22,
      "category": "Trees",
      "genus": "Bosnian Pine",
      "cultivar": "Emerald Arrow",
      "displayName": "Bosnian Pine 'Emerald Arrow'",
      "height": "12\u201315 ft",
      "width": "4\u20136 ft",
      "heightFt": 13.5,
      "widthFt": 5.0,
      "color": "Deep emerald green needles, columnar",
      "bloomTime": "Year-round",
      "spacing": "5\u20136 ft"
    },
    {
      "id": 23,
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Gin Fizz",
      "displayName": "Juniper 'Gin Fizz'",
      "height": "10\u201318 ft",
      "width": "7\u201310 ft",
      "heightFt": 14.0,
      "widthFt": 8.5,
      "color": "Blue-green foliage, heavy blue berries",
      "bloomTime": "Year-round",
      "spacing": "6\u20138 ft"
    },
    {
      "id": 24,
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Wichita Blue",
      "displayName": "Juniper 'Wichita Blue'",
      "height": "10\u201315 ft",
      "width": "4\u20136 ft",
      "heightFt": 12.5,
      "widthFt": 5.0,
      "color": "Bright sky-blue foliage, upright pyramidal",
      "bloomTime": "Year-round",
      "spacing": "5\u20136 ft"
    },
    {
      "id": 25,
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Torulosa",
      "displayName": "Juniper 'Torulosa'",
      "height": "12\u201315 ft",
      "width": "6\u20138 ft",
      "heightFt": 13.5,
      "widthFt": 7.0,
      "color": "Rich green twisted foliage, sculptural habit",
      "bloomTime": "Year-round",
      "spacing": "6\u20138 ft"
    },
    {
      "id": 26,
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Mint Julep",
      "displayName": "Juniper 'Mint Julep'",
      "height": "3\u20135 ft",
      "width": "4\u20136 ft",
      "heightFt": 4.0,
      "widthFt": 5.0,
      "color": "Mint-green foliage, arching branches",
      "bloomTime": "Year-round",
      "spacing": "4\u20135 ft"
    },
    {
      "id": 27,
      "category": "Trees",
      "genus": "Korean Fir",
      "cultivar": "Silberlocke",
      "displayName": "Korean Fir 'Silberlocke'",
      "height": "10\u201315 ft",
      "width": "6\u20138 ft",
      "heightFt": 12.5,
      "widthFt": 7.0,
      "color": "Curled green needles showing silver undersides",
      "bloomTime": "Year-round",
      "spacing": "6\u20138 ft"
    },
    {
      "id": 28,
      "category": "Shrubs",
      "genus": "Ninebark",
      "cultivar": "Summer Wine",
      "displayName": "Ninebark 'Summer Wine'",
      "height": "5\u20136 ft",
      "width": "5\u20136 ft",
      "heightFt": 5.5,
      "widthFt": 5.5,
      "color": "Pinkish-white flowers, dark purple foliage",
      "bloomTime": "Late Spring / Early Summer",
      "spacing": "5\u20136 ft"
    },
    {
      "id": 29,
      "category": "Shrubs",
      "genus": "Ninebark",
      "cultivar": "Autumn Jubilee",
      "displayName": "Ninebark 'Autumn Jubilee'",
      "height": "5\u20136 ft",
      "width": "4\u20135 ft",
      "heightFt": 5.5,
      "widthFt": 4.5,
      "color": "White flowers, golden-orange/purple fall foliage",
      "bloomTime": "Late Spring",
      "spacing": "4\u20135 ft"
    },
    {
      "id": 30,
      "category": "Shrubs",
      "genus": "Ninebark",
      "cultivar": "Little Devil",
      "displayName": "Ninebark 'Little Devil'",
      "height": "3\u20134 ft",
      "width": "3\u20134 ft",
      "heightFt": 3.5,
      "widthFt": 3.5,
      "color": "Pinkish-white button flowers, dark burgundy foliage",
      "bloomTime": "Late Spring",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 31,
      "category": "Shrubs",
      "genus": "Diervilla",
      "cultivar": "Diervilla lonicera (straight species)",
      "displayName": "Diervilla 'Diervilla lonicera (straight species)'",
      "height": "2\u20133 ft",
      "width": "3\u20134 ft",
      "heightFt": 2.5,
      "widthFt": 3.5,
      "color": "Yellow trumpet flowers, red fall foliage",
      "bloomTime": "Early to Mid Summer",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 32,
      "category": "Shrubs",
      "genus": "Diervilla",
      "cultivar": "Kodiak Black",
      "displayName": "Diervilla 'Kodiak Black'",
      "height": "3\u20134 ft",
      "width": "3\u20134 ft",
      "heightFt": 3.5,
      "widthFt": 3.5,
      "color": "Bright yellow flowers, dark purple/black foliage",
      "bloomTime": "Early to Late Summer",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 33,
      "category": "Shrubs",
      "genus": "Chokeberry",
      "cultivar": "Brilliantissima",
      "displayName": "Chokeberry 'Brilliantissima'",
      "height": "6\u20138 ft",
      "width": "6\u20138 ft",
      "heightFt": 7.0,
      "widthFt": 7.0,
      "color": "White flowers, red berries & fiery red fall foliage",
      "bloomTime": "Spring",
      "spacing": "6\u20138 ft"
    },
    {
      "id": 34,
      "category": "Shrubs",
      "genus": "Chokeberry",
      "cultivar": "Autumn Magic",
      "displayName": "Chokeberry 'Autumn Magic'",
      "height": "3\u20135 ft",
      "width": "2\u20134 ft",
      "heightFt": 4.0,
      "widthFt": 3.0,
      "color": "White flowers, dark purple berries & red fall color",
      "bloomTime": "Spring",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 35,
      "category": "Shrubs",
      "genus": "Chokeberry",
      "cultivar": "Low Scape Mound",
      "displayName": "Chokeberry 'Low Scape Mound'",
      "height": "1\u20132 ft",
      "width": "2 ft",
      "heightFt": 1.5,
      "widthFt": 2.0,
      "color": "White flowers, black berries, brilliant red fall foliage",
      "bloomTime": "Spring",
      "spacing": "1.5\u20132 ft"
    },
    {
      "id": 36,
      "category": "Shrubs",
      "genus": "American hazelnut",
      "cultivar": "Corylus americana (straight species)",
      "displayName": "American hazelnut 'Corylus americana (straight species)'",
      "height": "8\u201312 ft",
      "width": "8\u201310 ft",
      "heightFt": 10.0,
      "widthFt": 9.0,
      "color": "Yellow catkins, edible hazelnuts, orange/purple fall color",
      "bloomTime": "Early Spring (Catkins)",
      "spacing": "8\u201310 ft"
    },
    {
      "id": 37,
      "category": "Shrubs",
      "genus": "Virginia sweetspire",
      "cultivar": "Henry's Garnet",
      "displayName": "Virginia sweetspire 'Henry's Garnet'",
      "height": "3\u20135 ft",
      "width": "4\u20136 ft",
      "heightFt": 4.0,
      "widthFt": 5.0,
      "color": "Fragrant white bottle-brush flowers, garnet fall color",
      "bloomTime": "Early Summer",
      "spacing": "4\u20135 ft"
    },
    {
      "id": 38,
      "category": "Shrubs",
      "genus": "Virginia sweetspire",
      "cultivar": "Scentlandia",
      "displayName": "Virginia sweetspire 'Scentlandia'",
      "height": "2\u20133 ft",
      "width": "2\u20133 ft",
      "heightFt": 2.5,
      "widthFt": 2.5,
      "color": "Highly fragrant white flowers, intense red-purple fall color",
      "bloomTime": "Early Summer",
      "spacing": "2\u20133 ft"
    },
    {
      "id": 39,
      "category": "Shrubs",
      "genus": "Panicle hydrangea",
      "cultivar": "Limelight",
      "displayName": "Panicle hydrangea 'Limelight'",
      "height": "6\u20138 ft",
      "width": "6\u20138 ft",
      "heightFt": 7.0,
      "widthFt": 7.0,
      "color": "Lime green fading to white & pink blooms",
      "bloomTime": "Mid Summer to Fall",
      "spacing": "6\u20138 ft"
    },
    {
      "id": 40,
      "category": "Shrubs",
      "genus": "Panicle hydrangea",
      "cultivar": "Torch",
      "displayName": "Panicle hydrangea 'Torch'",
      "height": "3\u20135 ft",
      "width": "3\u20134 ft",
      "heightFt": 4.0,
      "widthFt": 3.5,
      "color": "Early blooming white to deep pink panicles",
      "bloomTime": "Early Summer to Fall",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 41,
      "category": "Shrubs",
      "genus": "Panicle hydrangea",
      "cultivar": "Quick Fire",
      "displayName": "Panicle hydrangea 'Quick Fire'",
      "height": "6\u20138 ft",
      "width": "6\u20138 ft",
      "heightFt": 7.0,
      "widthFt": 7.0,
      "color": "White flowers aging quickly to deep rose-pink",
      "bloomTime": "Early Summer to Fall",
      "spacing": "6\u20138 ft"
    },
    {
      "id": 42,
      "category": "Shrubs",
      "genus": "Fothergilla",
      "cultivar": "Mount Airy",
      "displayName": "Fothergilla 'Mount Airy'",
      "height": "3\u20135 ft",
      "width": "3\u20134 ft",
      "heightFt": 4.0,
      "widthFt": 3.5,
      "color": "Honey-scented white brush flowers, brilliant yellow-orange fall color",
      "bloomTime": "Spring",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 43,
      "category": "Shrubs",
      "genus": "Fothergilla",
      "cultivar": "Legend of the Fall",
      "displayName": "Fothergilla 'Legend of the Fall'",
      "height": "4\u20135 ft",
      "width": "4\u20135 ft",
      "heightFt": 4.5,
      "widthFt": 4.5,
      "color": "White bottle-brush flowers, vibrant multi-colored fall foliage",
      "bloomTime": "Spring",
      "spacing": "4\u20135 ft"
    },
    {
      "id": 44,
      "category": "Shrubs",
      "genus": "Fothergilla",
      "cultivar": "Blue Shadow",
      "displayName": "Fothergilla 'Blue Shadow'",
      "height": "4\u20135 ft",
      "width": "4\u20135 ft",
      "heightFt": 4.5,
      "widthFt": 4.5,
      "color": "White flowers, powdery blue summer foliage & fiery fall color",
      "bloomTime": "Spring",
      "spacing": "4\u20135 ft"
    },
    {
      "id": 45,
      "category": "Perennials",
      "genus": "Daffodils",
      "cultivar": "Thalia",
      "displayName": "Daffodils 'Thalia'",
      "height": "12\u201316 in",
      "width": "6 in",
      "heightFt": 1.17,
      "widthFt": 0.5,
      "color": "Pure white fragrant orchid-like blooms",
      "bloomTime": "Mid to Late Spring",
      "spacing": "4\u20136 in"
    },
    {
      "id": 46,
      "category": "Perennials",
      "genus": "Daffodils",
      "cultivar": "White Lion",
      "displayName": "Daffodils 'White Lion'",
      "height": "14\u201318 in",
      "width": "6 in",
      "heightFt": 1.33,
      "widthFt": 0.5,
      "color": "Double creamy white with yellow/apricot center",
      "bloomTime": "Mid to Late Spring",
      "spacing": "4\u20136 in"
    },
    {
      "id": 47,
      "category": "Perennials",
      "genus": "Daffodils",
      "cultivar": "Poeticus Recurvus",
      "displayName": "Daffodils 'Poeticus Recurvus'",
      "height": "14\u201316 in",
      "width": "6 in",
      "heightFt": 1.25,
      "widthFt": 0.5,
      "color": "White reflexed petals with tiny red-edged yellow cup",
      "bloomTime": "Late Spring",
      "spacing": "4\u20136 in"
    },
    {
      "id": 48,
      "category": "Perennials",
      "genus": "Daffodils",
      "cultivar": "Tahiti",
      "displayName": "Daffodils 'Tahiti'",
      "height": "14\u201316 in",
      "width": "6 in",
      "heightFt": 1.25,
      "widthFt": 0.5,
      "color": "Double golden yellow with orange-red accent petals",
      "bloomTime": "Mid Spring",
      "spacing": "4\u20136 in"
    },
    {
      "id": 49,
      "category": "Perennials",
      "genus": "Alliums",
      "cultivar": "Jackpot",
      "displayName": "Alliums 'Jackpot'",
      "height": "18\u201324 in",
      "width": "12\u201318 in",
      "heightFt": 1.75,
      "widthFt": 1.25,
      "color": "Large violet-purple globe clusters",
      "bloomTime": "Late Spring / Early Summer",
      "spacing": "12\u201315 in"
    },
    {
      "id": 50,
      "category": "Perennials",
      "genus": "Camassia",
      "cultivar": "Caerulea",
      "displayName": "Camassia 'Caerulea'",
      "height": "24\u201330 in",
      "width": "8\u201312 in",
      "heightFt": 2.25,
      "widthFt": 0.83,
      "color": "Star-shaped bright blue flower spikes",
      "bloomTime": "Late Spring",
      "spacing": "6\u20138 in"
    },
    {
      "id": 51,
      "category": "Perennials",
      "genus": "Leucojum",
      "cultivar": "Gravetye Giant",
      "displayName": "Leucojum 'Gravetye Giant'",
      "height": "18\u201324 in",
      "width": "8\u201312 in",
      "heightFt": 1.75,
      "widthFt": 0.83,
      "color": "White bell-shaped flowers tipped with green",
      "bloomTime": "Mid to Late Spring",
      "spacing": "6\u20138 in"
    },
    {
      "id": 52,
      "category": "Perennials",
      "genus": "Bearded iris",
      "cultivar": "Repeat The Blues",
      "displayName": "Bearded iris 'Repeat The Blues'",
      "height": "32\u201336 in",
      "width": "18\u201324 in",
      "heightFt": 2.83,
      "widthFt": 1.75,
      "color": "Soft lavender-blue reblooming flowers",
      "bloomTime": "Late Spring & Early Fall",
      "spacing": "18\u201324 in"
    },
    {
      "id": 53,
      "category": "Perennials",
      "genus": "Bearded iris",
      "cultivar": "Rhizome Cowboy",
      "displayName": "Bearded iris 'Rhizome Cowboy'",
      "height": "34\u201338 in",
      "width": "18\u201324 in",
      "heightFt": 3.0,
      "widthFt": 1.75,
      "color": "Tan/copper falls with violet-blue centers",
      "bloomTime": "Late Spring",
      "spacing": "18\u201324 in"
    },
    {
      "id": 54,
      "category": "Perennials",
      "genus": "Bearded iris",
      "cultivar": "Summer Olympics",
      "displayName": "Bearded iris 'Summer Olympics'",
      "height": "30\u201336 in",
      "width": "18\u201324 in",
      "heightFt": 2.75,
      "widthFt": 1.75,
      "color": "Cool yellow reblooming ruffled flowers",
      "bloomTime": "Late Spring & Late Summer",
      "spacing": "18\u201324 in"
    },
    {
      "id": 55,
      "category": "Perennials",
      "genus": "Bearded iris",
      "cultivar": "Mother Earth",
      "displayName": "Bearded iris 'Mother Earth'",
      "height": "34\u201336 in",
      "width": "18\u201324 in",
      "heightFt": 2.92,
      "widthFt": 1.75,
      "color": "Buff pink standards with lavender-blue falls",
      "bloomTime": "Late Spring",
      "spacing": "18\u201324 in"
    },
    {
      "id": 56,
      "category": "Perennials",
      "genus": "Baptisia",
      "cultivar": "Straight species",
      "displayName": "Baptisia 'Straight species'",
      "height": "3\u20134 ft",
      "width": "3\u20134 ft",
      "heightFt": 3.5,
      "widthFt": 3.5,
      "color": "Deep blue pea-like flowers",
      "bloomTime": "Late Spring / Early Summer",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 57,
      "category": "Perennials",
      "genus": "Baptisia",
      "cultivar": "American Goldfinch",
      "displayName": "Baptisia 'American Goldfinch'",
      "height": "3\u20133.5 ft",
      "width": "3.5\u20134 ft",
      "heightFt": 3.25,
      "widthFt": 3.75,
      "color": "Bright golden yellow flower spikes",
      "bloomTime": "Late Spring / Early Summer",
      "spacing": "3.5\u20134 ft"
    },
    {
      "id": 58,
      "category": "Perennials",
      "genus": "Baptisia",
      "cultivar": "Lemon Meringue",
      "displayName": "Baptisia 'Lemon Meringue'",
      "height": "3 ft",
      "width": "3 ft",
      "heightFt": 3.0,
      "widthFt": 3.0,
      "color": "Lemon yellow flower spikes on dark charcoal stems",
      "bloomTime": "Late Spring / Early Summer",
      "spacing": "3 ft"
    },
    {
      "id": 59,
      "category": "Perennials",
      "genus": "Columbine",
      "cultivar": "Eastern red columbine",
      "displayName": "Columbine 'Eastern red columbine'",
      "height": "18\u201324 in",
      "width": "12\u201318 in",
      "heightFt": 1.75,
      "widthFt": 1.25,
      "color": "Red and yellow bell-shaped drooping flowers",
      "bloomTime": "Late Spring to Early Summer",
      "spacing": "12\u201315 in"
    },
    {
      "id": 60,
      "category": "Perennials",
      "genus": "Garden phlox",
      "cultivar": "Jeana",
      "displayName": "Garden phlox 'Jeana'",
      "height": "3\u20134 ft",
      "width": "2\u20133 ft",
      "heightFt": 3.5,
      "widthFt": 2.5,
      "color": "Fragrant magenta-pink flower clusters (mildew resistant)",
      "bloomTime": "Mid Summer to Fall",
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": 61,
      "category": "Perennials",
      "genus": "Garden phlox",
      "cultivar": "David",
      "displayName": "Garden phlox 'David'",
      "height": "3\u20134 ft",
      "width": "2\u20133 ft",
      "heightFt": 3.5,
      "widthFt": 2.5,
      "color": "Fragrant pure white large flower heads",
      "bloomTime": "Mid Summer to Fall",
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": 62,
      "category": "Perennials",
      "genus": "Veronica",
      "cultivar": "Veronicastrum virginicum",
      "displayName": "Veronica 'Veronicastrum virginicum'",
      "height": "4\u20136 ft",
      "width": "2\u20133 ft",
      "heightFt": 5.0,
      "widthFt": 2.5,
      "color": "Pale blue to white slender candle-like spires",
      "bloomTime": "Mid to Late Summer",
      "spacing": "2\u20133 ft"
    },
    {
      "id": 63,
      "category": "Perennials",
      "genus": "Catmint",
      "cultivar": "Walker's Low",
      "displayName": "Catmint 'Walker's Low'",
      "height": "24\u201330 in",
      "width": "24\u201336 in",
      "heightFt": 2.25,
      "widthFt": 2.5,
      "color": "Lavender-blue aromatic flower spikes",
      "bloomTime": "Late Spring to Fall",
      "spacing": "24\u201330 in"
    },
    {
      "id": 64,
      "category": "Perennials",
      "genus": "Penstemon",
      "cultivar": "digitalis",
      "displayName": "Penstemon 'digitalis'",
      "height": "3\u20134 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 3.5,
      "widthFt": 1.75,
      "color": "White tubular bell flowers, dark foliage accent",
      "bloomTime": "Late Spring to Early Summer",
      "spacing": "18 in"
    },
    {
      "id": 65,
      "category": "Perennials",
      "genus": "Echinacea",
      "cultivar": "straight species",
      "displayName": "Echinacea 'straight species'",
      "height": "2\u20134 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 3.0,
      "widthFt": 1.75,
      "color": "Purple-pink petals with orange cone center",
      "bloomTime": "Early Summer to Early Fall",
      "spacing": "18\u201324 in"
    },
    {
      "id": 66,
      "category": "Perennials",
      "genus": "Monarda",
      "cultivar": "Jacob Cline",
      "displayName": "Monarda 'Jacob Cline'",
      "height": "3\u20134 ft",
      "width": "2\u20133 ft",
      "heightFt": 3.5,
      "widthFt": 2.5,
      "color": "Scarlet red whorled tubular flowers",
      "bloomTime": "Mid to Late Summer",
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": 67,
      "category": "Perennials",
      "genus": "Liatris",
      "cultivar": "Spicata",
      "displayName": "Liatris 'Spicata'",
      "height": "2\u20134 ft",
      "width": "1\u20131.5 ft",
      "heightFt": 3.0,
      "widthFt": 1.25,
      "color": "Purple fuzzy flower wands",
      "bloomTime": "Mid Summer",
      "spacing": "12\u201315 in"
    },
    {
      "id": 68,
      "category": "Perennials",
      "genus": "Rudbeckia",
      "cultivar": "Herbstsonne",
      "displayName": "Rudbeckia 'Herbstsonne'",
      "height": "5\u20137 ft",
      "width": "3\u20134 ft",
      "heightFt": 6.0,
      "widthFt": 3.5,
      "color": "Bright yellow drooping petals with green central cone",
      "bloomTime": "Late Summer to Fall",
      "spacing": "3 ft"
    },
    {
      "id": 69,
      "category": "Perennials",
      "genus": "Rudbeckia",
      "cultivar": "Goldsturm",
      "displayName": "Rudbeckia 'Goldsturm'",
      "height": "2\u20133 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 2.5,
      "widthFt": 1.75,
      "color": "Golden yellow daisy-like rays with dark brown cone",
      "bloomTime": "Mid Summer to Early Fall",
      "spacing": "18\u201324 in"
    },
    {
      "id": 70,
      "category": "Perennials",
      "genus": "Heliopsis",
      "cultivar": "Sunstruck",
      "displayName": "Heliopsis 'Sunstruck'",
      "height": "14\u201316 in",
      "width": "12\u201314 in",
      "heightFt": 1.25,
      "widthFt": 1.08,
      "color": "Golden yellow blooms with variegated white/green foliage",
      "bloomTime": "Summer to Early Fall",
      "spacing": "12\u201314 in"
    },
    {
      "id": 71,
      "category": "Perennials",
      "genus": "Asters",
      "cultivar": "Wood's Light Blue",
      "displayName": "Asters 'Wood's Light Blue'",
      "height": "12\u201318 in",
      "width": "12\u201318 in",
      "heightFt": 1.25,
      "widthFt": 1.25,
      "color": "Clear blue daisy-like flowers with yellow centers",
      "bloomTime": "Late Summer to Fall",
      "spacing": "12\u201315 in"
    },
    {
      "id": 72,
      "category": "Perennials",
      "genus": "Asters",
      "cultivar": "Purple Dome",
      "displayName": "Asters 'Purple Dome'",
      "height": "18\u201324 in",
      "width": "24\u201330 in",
      "heightFt": 1.75,
      "widthFt": 2.25,
      "color": "Deep royal purple dense flowers",
      "bloomTime": "Late Summer to Fall",
      "spacing": "20\u201324 in"
    },
    {
      "id": 73,
      "category": "Perennials",
      "genus": "Asters",
      "cultivar": "Raydon's Favorite",
      "displayName": "Asters 'Raydon's Favorite'",
      "height": "2\u20133 ft",
      "width": "2\u20133 ft",
      "heightFt": 2.5,
      "widthFt": 2.5,
      "color": "Aromatic lavender-blue starry blooms",
      "bloomTime": "Late Summer to Fall",
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": 74,
      "category": "Perennials",
      "genus": "Solidago",
      "cultivar": "Fireworks",
      "displayName": "Solidago 'Fireworks'",
      "height": "3\u20134 ft",
      "width": "2\u20133 ft",
      "heightFt": 3.5,
      "widthFt": 2.5,
      "color": "Golden yellow arching spray clusters",
      "bloomTime": "Late Summer to Fall",
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": 75,
      "category": "Perennials",
      "genus": "Boltonia",
      "cultivar": "Straight species",
      "displayName": "Boltonia 'Straight species'",
      "height": "4\u20135 ft",
      "width": "3\u20134 ft",
      "heightFt": 4.5,
      "widthFt": 3.5,
      "color": "White daisy-like flowers in profusion",
      "bloomTime": "Late Summer to Fall",
      "spacing": "3 ft"
    },
    {
      "id": 76,
      "category": "Perennials",
      "genus": "Japanese anemone",
      "cultivar": "Honorine Jobert",
      "displayName": "Japanese anemone 'Honorine Jobert'",
      "height": "3\u20134 ft",
      "width": "2\u20133 ft",
      "heightFt": 3.5,
      "widthFt": 2.5,
      "color": "Single pure white blooms with yellow stamens",
      "bloomTime": "Late Summer to Fall",
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": 77,
      "category": "Perennials",
      "genus": "Japanese anemone",
      "cultivar": "Wild Swan",
      "displayName": "Japanese anemone 'Wild Swan'",
      "height": "18\u201324 in",
      "width": "18\u201324 in",
      "heightFt": 1.75,
      "widthFt": 1.75,
      "color": "White petals with lavender-blue reverse streaks",
      "bloomTime": "Early Summer to Frost",
      "spacing": "18\u201320 in"
    },
    {
      "id": 78,
      "category": "Perennials",
      "genus": "Hollyhocks",
      "cultivar": "Alcea rugosa",
      "displayName": "Hollyhocks 'Alcea rugosa'",
      "height": "5\u20137 ft",
      "width": "2\u20133 ft",
      "heightFt": 6.0,
      "widthFt": 2.5,
      "color": "Single pale yellow trumpet flowers (rust resistant)",
      "bloomTime": "Early to Mid Summer",
      "spacing": "2\u20133 ft"
    },
    {
      "id": 79,
      "category": "Perennials",
      "genus": "Joe Pye Weed",
      "cultivar": "Purpureum",
      "displayName": "Joe Pye Weed 'Purpureum'",
      "height": "5\u20137 ft",
      "width": "3\u20134 ft",
      "heightFt": 6.0,
      "widthFt": 3.5,
      "color": "Mauve-purple large fragrant flower domes",
      "bloomTime": "Mid Summer to Fall",
      "spacing": "3\u20134 ft"
    },
    {
      "id": 80,
      "category": "Perennials",
      "genus": "Joe Pye Weed",
      "cultivar": "Baby Joe",
      "displayName": "Joe Pye Weed 'Baby Joe'",
      "height": "2\u20133 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 2.5,
      "widthFt": 1.75,
      "color": "Dwarf dusty pink/mauve flower heads",
      "bloomTime": "Mid Summer to Fall",
      "spacing": "2 ft"
    },
    {
      "id": 81,
      "category": "Perennials",
      "genus": "Helianthus",
      "cultivar": "Flore Pleno",
      "displayName": "Helianthus 'Flore Pleno'",
      "height": "4\u20136 ft",
      "width": "2\u20133 ft",
      "heightFt": 5.0,
      "widthFt": 2.5,
      "color": "Double bright yellow pom-pom flowers",
      "bloomTime": "Late Summer to Fall",
      "spacing": "2.5\u20133 ft"
    },
    {
      "id": 82,
      "category": "Grasses",
      "genus": "Little bluestem",
      "cultivar": "The Blues",
      "displayName": "Little bluestem 'The Blues'",
      "height": "2\u20133 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 2.5,
      "widthFt": 1.75,
      "color": "Blue-stemmed grass with bronze-red fall color",
      "bloomTime": "Late Summer (Plumes)",
      "spacing": "1.5\u20132 ft"
    },
    {
      "id": 83,
      "category": "Grasses",
      "genus": "Little bluestem",
      "cultivar": "Straight species",
      "displayName": "Little bluestem 'Straight species'",
      "height": "2\u20134 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 3.0,
      "widthFt": 1.75,
      "color": "Blue-green summer foliage, copper fall color",
      "bloomTime": "Late Summer (Plumes)",
      "spacing": "1.5\u20132 ft"
    },
    {
      "id": 84,
      "category": "Grasses",
      "genus": "Prairie dropseed",
      "cultivar": "Straight species",
      "displayName": "Prairie dropseed 'Straight species'",
      "height": "2\u20133 ft",
      "width": "2\u20133 ft",
      "heightFt": 2.5,
      "widthFt": 2.5,
      "color": "Fine green fountain foliage, fragrant copper blooms",
      "bloomTime": "Late Summer",
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": 85,
      "category": "Grasses",
      "genus": "Switchgrass",
      "cultivar": "Northwind",
      "displayName": "Switchgrass 'Northwind'",
      "height": "4\u20136 ft",
      "width": "2\u20133 ft",
      "heightFt": 5.0,
      "widthFt": 2.5,
      "color": "Olive green tight upright grass, yellow fall color",
      "bloomTime": "Late Summer",
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": 86,
      "category": "Grasses",
      "genus": "Switchgrass",
      "cultivar": "Shenandoah",
      "displayName": "Switchgrass 'Shenandoah'",
      "height": "3\u20134 ft",
      "width": "2\u20132.5 ft",
      "heightFt": 3.5,
      "widthFt": 2.25,
      "color": "Green blades with fiery red/burgundy tips",
      "bloomTime": "Late Summer",
      "spacing": "2 ft"
    },
    {
      "id": 87,
      "category": "Grasses",
      "genus": "Big bluestem",
      "cultivar": "Blackhawks",
      "displayName": "Big bluestem 'Blackhawks'",
      "height": "4\u20135 ft",
      "width": "2\u20132.5 ft",
      "heightFt": 4.5,
      "widthFt": 2.25,
      "color": "Dark green turning deep purple to near-black",
      "bloomTime": "Late Summer",
      "spacing": "2 ft"
    },
    {
      "id": 88,
      "category": "Low/filler plants",
      "genus": "Creeping phlox",
      "cultivar": "Emerald Blue",
      "displayName": "Creeping phlox 'Emerald Blue'",
      "height": "4\u20136 in",
      "width": "18\u201324 in",
      "heightFt": 0.42,
      "widthFt": 1.75,
      "color": "Lavender-blue star flowers, evergreen mat",
      "bloomTime": "Mid Spring",
      "spacing": "12\u201318 in"
    },
    {
      "id": 89,
      "category": "Low/filler plants",
      "genus": "Creeping thyme",
      "cultivar": "Elfin",
      "displayName": "Creeping thyme 'Elfin'",
      "height": "1\u20132 in",
      "width": "8\u201312 in",
      "heightFt": 0.12,
      "widthFt": 0.83,
      "color": "Pale pink/lavender tiny blooms, aromatic mat",
      "bloomTime": "Early Summer",
      "spacing": "6\u20138 in"
    },
    {
      "id": 90,
      "category": "Low/filler plants",
      "genus": "Creeping thyme",
      "cultivar": "Purple Carpet",
      "displayName": "Creeping thyme 'Purple Carpet'",
      "height": "2\u20134 in",
      "width": "12\u201318 in",
      "heightFt": 0.25,
      "widthFt": 1.25,
      "color": "Vibrant purple-magenta floral carpet",
      "bloomTime": "Early Summer",
      "spacing": "10\u201312 in"
    },
    {
      "id": 91,
      "category": "Low/filler plants",
      "genus": "Hardy geranium",
      "cultivar": "Rozanne",
      "displayName": "Hardy geranium 'Rozanne'",
      "height": "12\u201318 in",
      "width": "24\u201336 in",
      "heightFt": 1.25,
      "widthFt": 2.5,
      "color": "Violet-blue flowers with white centers",
      "bloomTime": "Late Spring to Frost",
      "spacing": "18\u201324 in"
    },
    {
      "id": 92,
      "category": "Low/filler plants",
      "genus": "Low sedums",
      "cultivar": "Voodoo",
      "displayName": "Low sedums 'Voodoo'",
      "height": "3\u20136 in",
      "width": "12\u201318 in",
      "heightFt": 0.38,
      "widthFt": 1.25,
      "color": "Deep crimson-red foliage, rosy-pink flowers",
      "bloomTime": "Mid to Late Summer",
      "spacing": "10\u201312 in"
    },
    {
      "id": 93,
      "category": "Low/filler plants",
      "genus": "Low sedums",
      "cultivar": "Angelina",
      "displayName": "Low sedums 'Angelina'",
      "height": "3\u20136 in",
      "width": "12\u201318 in",
      "heightFt": 0.38,
      "widthFt": 1.25,
      "color": "Golden yellow needle foliage, amber in winter",
      "bloomTime": "Mid Summer",
      "spacing": "10\u201312 in"
    },
    {
      "id": 94,
      "category": "Low/filler plants",
      "genus": "Low sedums",
      "cultivar": "Blue Spruce",
      "displayName": "Low sedums 'Blue Spruce'",
      "height": "4\u20136 in",
      "width": "12\u201318 in",
      "heightFt": 0.42,
      "widthFt": 1.25,
      "color": "Blue-green spruce-like foliage, yellow flowers",
      "bloomTime": "Mid Summer",
      "spacing": "10\u201312 in"
    },
    {
      "id": 95,
      "category": "Low/filler plants",
      "genus": "Lamb's ear",
      "cultivar": "Silver carpet",
      "displayName": "Lamb's ear 'Silver carpet'",
      "height": "6\u20138 in",
      "width": "18\u201324 in",
      "heightFt": 0.58,
      "widthFt": 1.75,
      "color": "Soft velvety silver foliage (non-blooming mat)",
      "bloomTime": "Foliage focus",
      "spacing": "12\u201315 in"
    },
    {
      "id": 96,
      "category": "Low/filler plants",
      "genus": "Iberis sempervirens",
      "cultivar": "Snowsation",
      "displayName": "Iberis sempervirens 'Snowsation'",
      "height": "6\u20138 in",
      "width": "12\u201315 in",
      "heightFt": 0.58,
      "widthFt": 1.12,
      "color": "Pure white dense flower clusters, evergreen",
      "bloomTime": "Spring",
      "spacing": "10\u201312 in"
    },
    {
      "id": 97,
      "category": "Vines",
      "genus": "Grapes",
      "cultivar": "Somerset Seedless",
      "displayName": "Grapes 'Somerset Seedless'",
      "height": "15\u201320 ft",
      "width": "6\u201310 ft",
      "heightFt": 17.5,
      "widthFt": 8.0,
      "color": "Inconspicuous blooms, sweet strawberry-flavored red grapes",
      "bloomTime": "Late Summer (Fruit)",
      "spacing": "8\u201310 ft"
    },
    {
      "id": 98,
      "category": "Vines",
      "genus": "Grapes",
      "cultivar": "Candice",
      "displayName": "Grapes 'Candice'",
      "height": "15\u201320 ft",
      "width": "6\u201310 ft",
      "heightFt": 17.5,
      "widthFt": 8.0,
      "color": "Inconspicuous blooms, sweet red seedless grapes",
      "bloomTime": "Late Summer (Fruit)",
      "spacing": "8\u201310 ft"
    },
    {
      "id": 99,
      "category": "Vines",
      "genus": "Clematis",
      "cultivar": "Virginiana",
      "displayName": "Clematis 'Virginiana'",
      "height": "12\u201320 ft",
      "width": "3\u20136 ft",
      "heightFt": 16.0,
      "widthFt": 4.5,
      "color": "Fragrant white starry flower clusters, feathery seed heads",
      "bloomTime": "Late Summer to Fall",
      "spacing": "4\u20136 ft"
    }
  ]
};
