const LOT_DATA = {
  "imageWidthFt": 141.79,
  "imagePxWidth": 1162,
  "imagePxHeight": 837,
  "seasons": [
    "Spring",
    "Early Summer",
    "Mid Summer",
    "Late Summer",
    "Fall"
  ],
  "plants": [
    {
      "id": "grasses-little-bluestem-the-blues",
      "category": "Grasses",
      "genus": "Little bluestem",
      "cultivar": "The Blues",
      "displayName": "Little bluestem 'The Blues'",
      "height": "2\u20133 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 2.5,
      "heightMinFt": 2.0,
      "heightMaxFt": 3.0,
      "widthFt": 1.75,
      "color": "Blue-stemmed grass with bronze-red fall color",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "1.5\u20132 ft"
    },
    {
      "id": "grasses-prairie-dropseed-straight-species",
      "category": "Grasses",
      "genus": "Prairie dropseed",
      "cultivar": "Straight species",
      "displayName": "Prairie dropseed",
      "height": "2\u20133 ft",
      "width": "2\u20133 ft",
      "heightFt": 2.5,
      "heightMinFt": 2.0,
      "heightMaxFt": 3.0,
      "widthFt": 2.5,
      "color": "Fine green fountain foliage, fragrant copper blooms",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": "grasses-little-bluestem-straight-species",
      "category": "Grasses",
      "genus": "Little bluestem",
      "cultivar": "Straight species",
      "displayName": "Little bluestem",
      "height": "2\u20134 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 3.0,
      "heightMinFt": 2.0,
      "heightMaxFt": 4.0,
      "widthFt": 1.75,
      "color": "Blue-green summer foliage, copper fall color",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "1.5\u20132 ft"
    },
    {
      "id": "grasses-switchgrass-shenandoah",
      "category": "Grasses",
      "genus": "Switchgrass",
      "cultivar": "Shenandoah",
      "displayName": "Switchgrass 'Shenandoah'",
      "height": "3\u20134 ft",
      "width": "2\u20132.5 ft",
      "heightFt": 3.5,
      "heightMinFt": 3.0,
      "heightMaxFt": 4.0,
      "widthFt": 2.25,
      "color": "Green blades with fiery red/burgundy tips",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "2 ft"
    },
    {
      "id": "grasses-big-bluestem-blackhawks",
      "category": "Grasses",
      "genus": "Big bluestem",
      "cultivar": "Blackhawks",
      "displayName": "Big bluestem 'Blackhawks'",
      "height": "4\u20135 ft",
      "width": "2\u20132.5 ft",
      "heightFt": 4.5,
      "heightMinFt": 4.0,
      "heightMaxFt": 5.0,
      "widthFt": 2.25,
      "color": "Dark green turning deep purple to near-black",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "2 ft"
    },
    {
      "id": "grasses-switchgrass-northwind",
      "category": "Grasses",
      "genus": "Switchgrass",
      "cultivar": "Northwind",
      "displayName": "Switchgrass 'Northwind'",
      "height": "4\u20136 ft",
      "width": "2\u20133 ft",
      "heightFt": 5.0,
      "heightMinFt": 4.0,
      "heightMaxFt": 6.0,
      "widthFt": 2.5,
      "color": "Olive green tight upright grass, yellow fall color",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": "low-filler-plants-creeping-thyme-elfin",
      "category": "Low/filler plants",
      "genus": "Creeping thyme",
      "cultivar": "Elfin",
      "displayName": "Creeping thyme 'Elfin'",
      "height": "1\u20132 in",
      "width": "8\u201312 in",
      "heightFt": 0.12,
      "heightMinFt": 0.08,
      "heightMaxFt": 0.17,
      "widthFt": 0.83,
      "color": "Pale pink/lavender tiny blooms, aromatic mat",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "6\u20138 in"
    },
    {
      "id": "low-filler-plants-hardy-geranium-rozanne",
      "category": "Low/filler plants",
      "genus": "Hardy geranium",
      "cultivar": "Rozanne",
      "displayName": "Hardy geranium 'Rozanne'",
      "height": "12\u201318 in",
      "width": "24\u201336 in",
      "heightFt": 1.25,
      "heightMinFt": 1.0,
      "heightMaxFt": 1.5,
      "widthFt": 2.5,
      "color": "Violet-blue flowers with white centers",
      "bloomTime": "Early Summer, Mid Summer, Late Summer, Fall",
      "seasons": [
        "Early Summer",
        "Mid Summer",
        "Late Summer",
        "Fall"
      ],
      "spacing": "18\u201324 in"
    },
    {
      "id": "low-filler-plants-creeping-thyme-purple-carpet",
      "category": "Low/filler plants",
      "genus": "Creeping thyme",
      "cultivar": "Purple Carpet",
      "displayName": "Creeping thyme 'Purple Carpet'",
      "height": "2\u20134 in",
      "width": "12\u201318 in",
      "heightFt": 0.25,
      "heightMinFt": 0.17,
      "heightMaxFt": 0.33,
      "widthFt": 1.25,
      "color": "Vibrant purple-magenta floral carpet",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "10\u201312 in"
    },
    {
      "id": "low-filler-plants-low-sedums-voodoo",
      "category": "Low/filler plants",
      "genus": "Low sedums",
      "cultivar": "Voodoo",
      "displayName": "Low sedums 'Voodoo'",
      "height": "3\u20136 in",
      "width": "12\u201318 in",
      "heightFt": 0.38,
      "heightMinFt": 0.25,
      "heightMaxFt": 0.5,
      "widthFt": 1.25,
      "color": "Deep crimson-red foliage, rosy-pink flowers",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "10\u201312 in"
    },
    {
      "id": "low-filler-plants-low-sedums-angelina",
      "category": "Low/filler plants",
      "genus": "Low sedums",
      "cultivar": "Angelina",
      "displayName": "Low sedums 'Angelina'",
      "height": "3\u20136 in",
      "width": "12\u201318 in",
      "heightFt": 0.38,
      "heightMinFt": 0.25,
      "heightMaxFt": 0.5,
      "widthFt": 1.25,
      "color": "Golden yellow needle foliage, amber in winter",
      "bloomTime": "Mid Summer",
      "seasons": [
        "Mid Summer"
      ],
      "spacing": "10\u201312 in"
    },
    {
      "id": "low-filler-plants-low-sedums-blue-spruce",
      "category": "Low/filler plants",
      "genus": "Low sedums",
      "cultivar": "Blue Spruce",
      "displayName": "Low sedums 'Blue Spruce'",
      "height": "4\u20136 in",
      "width": "12\u201318 in",
      "heightFt": 0.42,
      "heightMinFt": 0.33,
      "heightMaxFt": 0.5,
      "widthFt": 1.25,
      "color": "Blue-green spruce-like foliage, yellow flowers",
      "bloomTime": "Mid Summer",
      "seasons": [
        "Mid Summer"
      ],
      "spacing": "10\u201312 in"
    },
    {
      "id": "low-filler-plants-creeping-phlox-emerald-blue",
      "category": "Low/filler plants",
      "genus": "Creeping phlox",
      "cultivar": "Emerald Blue",
      "displayName": "Creeping phlox 'Emerald Blue'",
      "height": "4\u20136 in",
      "width": "18\u201324 in",
      "heightFt": 0.42,
      "heightMinFt": 0.33,
      "heightMaxFt": 0.5,
      "widthFt": 1.75,
      "color": "Lavender-blue star flowers, evergreen mat",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "12\u201318 in"
    },
    {
      "id": "low-filler-plants-iberis-sempervirens-snowsation",
      "category": "Low/filler plants",
      "genus": "Iberis sempervirens",
      "cultivar": "Snowsation",
      "displayName": "Iberis sempervirens 'Snowsation'",
      "height": "6\u20138 in",
      "width": "12\u201315 in",
      "heightFt": 0.58,
      "heightMinFt": 0.5,
      "heightMaxFt": 0.67,
      "widthFt": 1.12,
      "color": "Pure white dense flower clusters, evergreen",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "10\u201312 in"
    },
    {
      "id": "low-filler-plants-lamb-s-ear-silver-carpet",
      "category": "Low/filler plants",
      "genus": "Lamb's ear",
      "cultivar": "Silver carpet",
      "displayName": "Lamb's ear 'Silver carpet'",
      "height": "6\u20138 in",
      "width": "18\u201324 in",
      "heightFt": 0.58,
      "heightMinFt": 0.5,
      "heightMaxFt": 0.67,
      "widthFt": 1.75,
      "color": "Soft velvety silver foliage (non-blooming mat)",
      "bloomTime": "Mid Summer",
      "seasons": [
        "Mid Summer"
      ],
      "spacing": "12\u201315 in"
    },
    {
      "id": "perennials-daffodils-thalia",
      "category": "Perennials",
      "genus": "Daffodils",
      "cultivar": "Thalia",
      "displayName": "Daffodils 'Thalia'",
      "height": "12\u201316 in",
      "width": "6 in",
      "heightFt": 1.17,
      "heightMinFt": 1.0,
      "heightMaxFt": 1.33,
      "widthFt": 0.5,
      "color": "Pure white fragrant orchid-like blooms",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "4\u20136 in"
    },
    {
      "id": "perennials-asters-wood-s-light-blue",
      "category": "Perennials",
      "genus": "Asters",
      "cultivar": "Wood's Light Blue",
      "displayName": "Asters 'Wood's Light Blue'",
      "height": "12\u201318 in",
      "width": "12\u201318 in",
      "heightFt": 1.25,
      "heightMinFt": 1.0,
      "heightMaxFt": 1.5,
      "widthFt": 1.25,
      "color": "Clear blue daisy-like flowers with yellow centers",
      "bloomTime": "Fall",
      "seasons": [
        "Fall"
      ],
      "spacing": "12\u201315 in"
    },
    {
      "id": "perennials-heliopsis-sunstruck",
      "category": "Perennials",
      "genus": "Heliopsis",
      "cultivar": "Sunstruck",
      "displayName": "Heliopsis 'Sunstruck'",
      "height": "14\u201316 in",
      "width": "12\u201314 in",
      "heightFt": 1.25,
      "heightMinFt": 1.17,
      "heightMaxFt": 1.33,
      "widthFt": 1.08,
      "color": "Golden yellow blooms with variegated white/green foliage",
      "bloomTime": "Mid Summer",
      "seasons": [
        "Mid Summer"
      ],
      "spacing": "12\u201314 in"
    },
    {
      "id": "perennials-daffodils-poeticus-recurvus",
      "category": "Perennials",
      "genus": "Daffodils",
      "cultivar": "Poeticus Recurvus",
      "displayName": "Daffodils 'Poeticus Recurvus'",
      "height": "14\u201316 in",
      "width": "6 in",
      "heightFt": 1.25,
      "heightMinFt": 1.17,
      "heightMaxFt": 1.33,
      "widthFt": 0.5,
      "color": "White reflexed petals with tiny red-edged yellow cup",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "4\u20136 in"
    },
    {
      "id": "perennials-daffodils-tahiti",
      "category": "Perennials",
      "genus": "Daffodils",
      "cultivar": "Tahiti",
      "displayName": "Daffodils 'Tahiti'",
      "height": "14\u201316 in",
      "width": "6 in",
      "heightFt": 1.25,
      "heightMinFt": 1.17,
      "heightMaxFt": 1.33,
      "widthFt": 0.5,
      "color": "Double golden yellow with orange-red accent petals",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "4\u20136 in"
    },
    {
      "id": "perennials-daffodils-white-lion",
      "category": "Perennials",
      "genus": "Daffodils",
      "cultivar": "White Lion",
      "displayName": "Daffodils 'White Lion'",
      "height": "14\u201318 in",
      "width": "6 in",
      "heightFt": 1.33,
      "heightMinFt": 1.17,
      "heightMaxFt": 1.5,
      "widthFt": 0.5,
      "color": "Double creamy white with yellow/apricot center",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "4\u20136 in"
    },
    {
      "id": "perennials-alliums-jackpot",
      "category": "Perennials",
      "genus": "Alliums",
      "cultivar": "Jackpot",
      "displayName": "Alliums 'Jackpot'",
      "height": "18\u201324 in",
      "width": "12\u201318 in",
      "heightFt": 1.75,
      "heightMinFt": 1.5,
      "heightMaxFt": 2.0,
      "widthFt": 1.25,
      "color": "Large violet-purple globe clusters",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "12\u201315 in"
    },
    {
      "id": "perennials-columbine-eastern-red-columbine",
      "category": "Perennials",
      "genus": "Columbine",
      "cultivar": "Eastern red columbine",
      "displayName": "Columbine 'Eastern red columbine'",
      "height": "18\u201324 in",
      "width": "12\u201318 in",
      "heightFt": 1.75,
      "heightMinFt": 1.5,
      "heightMaxFt": 2.0,
      "widthFt": 1.25,
      "color": "Red and yellow bell-shaped drooping flowers",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "12\u201315 in"
    },
    {
      "id": "perennials-japanese-anemone-wild-swan",
      "category": "Perennials",
      "genus": "Japanese anemone",
      "cultivar": "Wild Swan",
      "displayName": "Japanese anemone 'Wild Swan'",
      "height": "18\u201324 in",
      "width": "18\u201324 in",
      "heightFt": 1.75,
      "heightMinFt": 1.5,
      "heightMaxFt": 2.0,
      "widthFt": 1.75,
      "color": "White petals with lavender-blue reverse streaks",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "18\u201320 in"
    },
    {
      "id": "perennials-asters-purple-dome",
      "category": "Perennials",
      "genus": "Asters",
      "cultivar": "Purple Dome",
      "displayName": "Asters 'Purple Dome'",
      "height": "18\u201324 in",
      "width": "24\u201330 in",
      "heightFt": 1.75,
      "heightMinFt": 1.5,
      "heightMaxFt": 2.0,
      "widthFt": 2.25,
      "color": "Deep royal purple dense flowers",
      "bloomTime": "Fall",
      "seasons": [
        "Fall"
      ],
      "spacing": "20\u201324 in"
    },
    {
      "id": "perennials-leucojum-gravetye-giant",
      "category": "Perennials",
      "genus": "Leucojum",
      "cultivar": "Gravetye Giant",
      "displayName": "Leucojum 'Gravetye Giant'",
      "height": "18\u201324 in",
      "width": "8\u201312 in",
      "heightFt": 1.75,
      "heightMinFt": 1.5,
      "heightMaxFt": 2.0,
      "widthFt": 0.83,
      "color": "White bell-shaped flowers tipped with green",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "6\u20138 in"
    },
    {
      "id": "perennials-rudbeckia-goldsturm",
      "category": "Perennials",
      "genus": "Rudbeckia",
      "cultivar": "Goldsturm",
      "displayName": "Rudbeckia 'Goldsturm'",
      "height": "2\u20133 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 2.5,
      "heightMinFt": 2.0,
      "heightMaxFt": 3.0,
      "widthFt": 1.75,
      "color": "Golden yellow daisy-like rays with dark brown cone",
      "bloomTime": "Mid Summer",
      "seasons": [
        "Mid Summer"
      ],
      "spacing": "18\u201324 in"
    },
    {
      "id": "perennials-joe-pye-weed-baby-joe",
      "category": "Perennials",
      "genus": "Joe Pye Weed",
      "cultivar": "Baby Joe",
      "displayName": "Joe Pye Weed 'Baby Joe'",
      "height": "2\u20133 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 2.5,
      "heightMinFt": 2.0,
      "heightMaxFt": 3.0,
      "widthFt": 1.75,
      "color": "Dwarf dusty pink/mauve flower heads",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "2 ft"
    },
    {
      "id": "perennials-asters-raydon-s-favorite",
      "category": "Perennials",
      "genus": "Asters",
      "cultivar": "Raydon's Favorite",
      "displayName": "Asters 'Raydon's Favorite'",
      "height": "2\u20133 ft",
      "width": "2\u20133 ft",
      "heightFt": 2.5,
      "heightMinFt": 2.0,
      "heightMaxFt": 3.0,
      "widthFt": 2.5,
      "color": "Aromatic lavender-blue starry blooms",
      "bloomTime": "Fall",
      "seasons": [
        "Fall"
      ],
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": "perennials-liatris-spicata",
      "category": "Perennials",
      "genus": "Liatris",
      "cultivar": "Spicata",
      "displayName": "Liatris 'Spicata'",
      "height": "2\u20134 ft",
      "width": "1\u20131.5 ft",
      "heightFt": 3.0,
      "heightMinFt": 2.0,
      "heightMaxFt": 4.0,
      "widthFt": 1.25,
      "color": "Purple fuzzy flower wands",
      "bloomTime": "Mid Summer",
      "seasons": [
        "Mid Summer"
      ],
      "spacing": "12\u201315 in"
    },
    {
      "id": "perennials-echinacea-straight-species",
      "category": "Perennials",
      "genus": "Echinacea",
      "cultivar": "straight species",
      "displayName": "Echinacea",
      "height": "2\u20134 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 3.0,
      "heightMinFt": 2.0,
      "heightMaxFt": 4.0,
      "widthFt": 1.75,
      "color": "Purple-pink petals with orange cone center",
      "bloomTime": "Mid Summer, Late Summer",
      "seasons": [
        "Mid Summer",
        "Late Summer"
      ],
      "spacing": "18\u201324 in"
    },
    {
      "id": "perennials-catmint-walker-s-low",
      "category": "Perennials",
      "genus": "Catmint",
      "cultivar": "Walker's Low",
      "displayName": "Catmint 'Walker's Low'",
      "height": "24\u201330 in",
      "width": "24\u201336 in",
      "heightFt": 2.25,
      "heightMinFt": 2.0,
      "heightMaxFt": 2.5,
      "widthFt": 2.5,
      "color": "Lavender-blue aromatic flower spikes",
      "bloomTime": "Early Summer, Late Summer",
      "seasons": [
        "Early Summer",
        "Late Summer"
      ],
      "spacing": "24\u201330 in"
    },
    {
      "id": "perennials-camassia-caerulea",
      "category": "Perennials",
      "genus": "Camassia",
      "cultivar": "Caerulea",
      "displayName": "Camassia 'Caerulea'",
      "height": "24\u201330 in",
      "width": "8\u201312 in",
      "heightFt": 2.25,
      "heightMinFt": 2.0,
      "heightMaxFt": 2.5,
      "widthFt": 0.83,
      "color": "Star-shaped bright blue flower spikes",
      "bloomTime": "Late Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "6\u20138 in"
    },
    {
      "id": "perennials-baptisia-lemon-meringue",
      "category": "Perennials",
      "genus": "Baptisia",
      "cultivar": "Lemon Meringue",
      "displayName": "Baptisia 'Lemon Meringue'",
      "height": "3 ft",
      "width": "3 ft",
      "heightFt": 3.0,
      "heightMinFt": 3.0,
      "heightMaxFt": 3.0,
      "widthFt": 3.0,
      "color": "Lemon yellow flower spikes on dark charcoal stems",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "3 ft"
    },
    {
      "id": "perennials-baptisia-american-goldfinch",
      "category": "Perennials",
      "genus": "Baptisia",
      "cultivar": "American Goldfinch",
      "displayName": "Baptisia 'American Goldfinch'",
      "height": "3\u20133.5 ft",
      "width": "3.5\u20134 ft",
      "heightFt": 3.25,
      "heightMinFt": 3.0,
      "heightMaxFt": 3.5,
      "widthFt": 3.75,
      "color": "Bright golden yellow flower spikes",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "3.5\u20134 ft"
    },
    {
      "id": "perennials-penstemon-digitalis",
      "category": "Perennials",
      "genus": "Penstemon",
      "cultivar": "digitalis",
      "displayName": "Penstemon 'digitalis'",
      "height": "3\u20134 ft",
      "width": "1.5\u20132 ft",
      "heightFt": 3.5,
      "heightMinFt": 3.0,
      "heightMaxFt": 4.0,
      "widthFt": 1.75,
      "color": "White tubular bell flowers, dark foliage accent",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "18 in"
    },
    {
      "id": "perennials-garden-phlox-jeana",
      "category": "Perennials",
      "genus": "Garden phlox",
      "cultivar": "Jeana",
      "displayName": "Garden phlox 'Jeana'",
      "height": "3\u20134 ft",
      "width": "2\u20133 ft",
      "heightFt": 3.5,
      "heightMinFt": 3.0,
      "heightMaxFt": 4.0,
      "widthFt": 2.5,
      "color": "Fragrant magenta-pink flower clusters (mildew resistant)",
      "bloomTime": "Mid Summer, Late Summer",
      "seasons": [
        "Mid Summer",
        "Late Summer"
      ],
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": "perennials-garden-phlox-david",
      "category": "Perennials",
      "genus": "Garden phlox",
      "cultivar": "David",
      "displayName": "Garden phlox 'David'",
      "height": "3\u20134 ft",
      "width": "2\u20133 ft",
      "heightFt": 3.5,
      "heightMinFt": 3.0,
      "heightMaxFt": 4.0,
      "widthFt": 2.5,
      "color": "Fragrant pure white large flower heads",
      "bloomTime": "Mid Summer, Late Summer",
      "seasons": [
        "Mid Summer",
        "Late Summer"
      ],
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": "perennials-monarda-jacob-cline",
      "category": "Perennials",
      "genus": "Monarda",
      "cultivar": "Jacob Cline",
      "displayName": "Monarda 'Jacob Cline'",
      "height": "3\u20134 ft",
      "width": "2\u20133 ft",
      "heightFt": 3.5,
      "heightMinFt": 3.0,
      "heightMaxFt": 4.0,
      "widthFt": 2.5,
      "color": "Scarlet red whorled tubular flowers",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": "perennials-solidago-fireworks",
      "category": "Perennials",
      "genus": "Solidago",
      "cultivar": "Fireworks",
      "displayName": "Solidago 'Fireworks'",
      "height": "3\u20134 ft",
      "width": "2\u20133 ft",
      "heightFt": 3.5,
      "heightMinFt": 3.0,
      "heightMaxFt": 4.0,
      "widthFt": 2.5,
      "color": "Golden yellow arching spray clusters",
      "bloomTime": "Late Summer, Fall",
      "seasons": [
        "Late Summer",
        "Fall"
      ],
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": "perennials-japanese-anemone-honorine-jobert",
      "category": "Perennials",
      "genus": "Japanese anemone",
      "cultivar": "Honorine Jobert",
      "displayName": "Japanese anemone 'Honorine Jobert'",
      "height": "3\u20134 ft",
      "width": "2\u20133 ft",
      "heightFt": 3.5,
      "heightMinFt": 3.0,
      "heightMaxFt": 4.0,
      "widthFt": 2.5,
      "color": "Single pure white blooms with yellow stamens",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "2\u20132.5 ft"
    },
    {
      "id": "perennials-baptisia-straight-species",
      "category": "Perennials",
      "genus": "Baptisia",
      "cultivar": "Straight species",
      "displayName": "Baptisia",
      "height": "3\u20134 ft",
      "width": "3\u20134 ft",
      "heightFt": 3.5,
      "heightMinFt": 3.0,
      "heightMaxFt": 4.0,
      "widthFt": 3.5,
      "color": "Deep blue pea-like flowers",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "perennials-bearded-iris-summer-olympics",
      "category": "Perennials",
      "genus": "Bearded iris",
      "cultivar": "Summer Olympics",
      "displayName": "Bearded iris 'Summer Olympics'",
      "height": "30\u201336 in",
      "width": "18\u201324 in",
      "heightFt": 2.75,
      "heightMinFt": 2.5,
      "heightMaxFt": 3.0,
      "widthFt": 1.75,
      "color": "Cool yellow reblooming ruffled flowers",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "18\u201324 in"
    },
    {
      "id": "perennials-bearded-iris-repeat-the-blues",
      "category": "Perennials",
      "genus": "Bearded iris",
      "cultivar": "Repeat The Blues",
      "displayName": "Bearded iris 'Repeat The Blues'",
      "height": "14 in",
      "width": "18\u201324 in",
      "heightFt": 1.17,
      "heightMinFt": 1.17,
      "heightMaxFt": 1.17,
      "widthFt": 1.75,
      "color": "Soft lavender-blue reblooming flowers",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "18\u201324 in"
    },
    {
      "id": "perennials-bearded-iris-mother-earth",
      "category": "Perennials",
      "genus": "Bearded iris",
      "cultivar": "Mother Earth",
      "displayName": "Bearded iris 'Mother Earth'",
      "height": "34\u201336 in",
      "width": "18\u201324 in",
      "heightFt": 2.92,
      "heightMinFt": 2.83,
      "heightMaxFt": 3.0,
      "widthFt": 1.75,
      "color": "Buff pink standards with lavender-blue falls",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "18\u201324 in"
    },
    {
      "id": "perennials-bearded-iris-rhizome-cowboy",
      "category": "Perennials",
      "genus": "Bearded iris",
      "cultivar": "Rhizome Cowboy",
      "displayName": "Bearded iris 'Rhizome Cowboy'",
      "height": "34\u201338 in",
      "width": "18\u201324 in",
      "heightFt": 3.0,
      "heightMinFt": 2.83,
      "heightMaxFt": 3.17,
      "widthFt": 1.75,
      "color": "Tan/copper falls with violet-blue centers",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "18\u201324 in"
    },
    {
      "id": "perennials-boltonia-straight-species",
      "category": "Perennials",
      "genus": "Boltonia",
      "cultivar": "Straight species",
      "displayName": "Boltonia",
      "height": "4\u20135 ft",
      "width": "3\u20134 ft",
      "heightFt": 4.5,
      "heightMinFt": 4.0,
      "heightMaxFt": 5.0,
      "widthFt": 3.5,
      "color": "White daisy-like flowers in profusion",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "3 ft"
    },
    {
      "id": "perennials-veronica-veronicastrum-virginicum",
      "category": "Perennials",
      "genus": "Veronica",
      "cultivar": "Veronicastrum virginicum",
      "displayName": "Veronica 'Veronicastrum virginicum'",
      "height": "4\u20136 ft",
      "width": "2\u20133 ft",
      "heightFt": 5.0,
      "heightMinFt": 4.0,
      "heightMaxFt": 6.0,
      "widthFt": 2.5,
      "color": "Pale blue to white slender candle-like spires",
      "bloomTime": "Mid Summer",
      "seasons": [
        "Mid Summer"
      ],
      "spacing": "2\u20133 ft"
    },
    {
      "id": "perennials-helianthus-flore-pleno",
      "category": "Perennials",
      "genus": "Helianthus",
      "cultivar": "Flore Pleno",
      "displayName": "Helianthus 'Flore Pleno'",
      "height": "4\u20136 ft",
      "width": "2\u20133 ft",
      "heightFt": 5.0,
      "heightMinFt": 4.0,
      "heightMaxFt": 6.0,
      "widthFt": 2.5,
      "color": "Double bright yellow pom-pom flowers",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "2.5\u20133 ft"
    },
    {
      "id": "perennials-hollyhocks-alcea-rugosa",
      "category": "Perennials",
      "genus": "Hollyhocks",
      "cultivar": "Alcea rugosa",
      "displayName": "Hollyhocks 'Alcea rugosa'",
      "height": "5\u20137 ft",
      "width": "2\u20133 ft",
      "heightFt": 6.0,
      "heightMinFt": 5.0,
      "heightMaxFt": 7.0,
      "widthFt": 2.5,
      "color": "Single pale yellow trumpet flowers (rust resistant)",
      "bloomTime": "Mid Summer",
      "seasons": [
        "Mid Summer"
      ],
      "spacing": "2\u20133 ft"
    },
    {
      "id": "perennials-rudbeckia-herbstsonne",
      "category": "Perennials",
      "genus": "Rudbeckia",
      "cultivar": "Herbstsonne",
      "displayName": "Rudbeckia 'Herbstsonne'",
      "height": "5\u20137 ft",
      "width": "3\u20134 ft",
      "heightFt": 6.0,
      "heightMinFt": 5.0,
      "heightMaxFt": 7.0,
      "widthFt": 3.5,
      "color": "Bright yellow drooping petals with green central cone",
      "bloomTime": "Mid Summer, Late Summer",
      "seasons": [
        "Mid Summer",
        "Late Summer"
      ],
      "spacing": "3 ft"
    },
    {
      "id": "perennials-joe-pye-weed-purpureum",
      "category": "Perennials",
      "genus": "Joe Pye Weed",
      "cultivar": "Purpureum",
      "displayName": "Joe Pye Weed 'Purpureum'",
      "height": "5\u20137 ft",
      "width": "3\u20134 ft",
      "heightFt": 6.0,
      "heightMinFt": 5.0,
      "heightMaxFt": 7.0,
      "widthFt": 3.5,
      "color": "Mauve-purple large fragrant flower domes",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "shrubs-chokeberry-low-scape-mound",
      "category": "Shrubs",
      "genus": "Chokeberry",
      "cultivar": "Low Scape Mound",
      "displayName": "Chokeberry 'Low Scape Mound'",
      "height": "1\u20132 ft",
      "width": "2 ft",
      "heightFt": 1.5,
      "heightMinFt": 1.0,
      "heightMaxFt": 2.0,
      "widthFt": 2.0,
      "color": "White flowers, black berries, brilliant red fall foliage",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "1.5\u20132 ft"
    },
    {
      "id": "shrubs-virginia-sweetspire-scentlandia",
      "category": "Shrubs",
      "genus": "Virginia sweetspire",
      "cultivar": "Scentlandia",
      "displayName": "Virginia sweetspire 'Scentlandia'",
      "height": "2\u20133 ft",
      "width": "2\u20133 ft",
      "heightFt": 2.5,
      "heightMinFt": 2.0,
      "heightMaxFt": 3.0,
      "widthFt": 2.5,
      "color": "Highly fragrant white flowers, intense red-purple fall color",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "2\u20133 ft"
    },
    {
      "id": "shrubs-diervilla-diervilla-lonicera-straight-species",
      "category": "Shrubs",
      "genus": "Diervilla",
      "cultivar": "Diervilla lonicera (straight species)",
      "displayName": "Diervilla 'Diervilla lonicera (straight species)'",
      "height": "2\u20133 ft",
      "width": "3\u20134 ft",
      "heightFt": 2.5,
      "heightMinFt": 2.0,
      "heightMaxFt": 3.0,
      "widthFt": 3.5,
      "color": "Yellow trumpet flowers, red fall foliage",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "shrubs-ninebark-little-devil",
      "category": "Shrubs",
      "genus": "Ninebark",
      "cultivar": "Little Devil",
      "displayName": "Ninebark 'Little Devil'",
      "height": "3\u20134 ft",
      "width": "3\u20134 ft",
      "heightFt": 3.5,
      "heightMinFt": 3.0,
      "heightMaxFt": 4.0,
      "widthFt": 3.5,
      "color": "Pinkish-white button flowers, dark burgundy foliage",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "shrubs-diervilla-kodiak-black",
      "category": "Shrubs",
      "genus": "Diervilla",
      "cultivar": "Kodiak Black",
      "displayName": "Diervilla 'Kodiak Black'",
      "height": "3\u20134 ft",
      "width": "3\u20134 ft",
      "heightFt": 3.5,
      "heightMinFt": 3.0,
      "heightMaxFt": 4.0,
      "widthFt": 3.5,
      "color": "Bright yellow flowers, dark purple/black foliage",
      "bloomTime": "Mid Summer",
      "seasons": [
        "Mid Summer"
      ],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "shrubs-chokeberry-autumn-magic",
      "category": "Shrubs",
      "genus": "Chokeberry",
      "cultivar": "Autumn Magic",
      "displayName": "Chokeberry 'Autumn Magic'",
      "height": "3\u20135 ft",
      "width": "2\u20134 ft",
      "heightFt": 4.0,
      "heightMinFt": 3.0,
      "heightMaxFt": 5.0,
      "widthFt": 3.0,
      "color": "White flowers, dark purple berries & red fall color",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "shrubs-panicle-hydrangea-torch",
      "category": "Shrubs",
      "genus": "Panicle hydrangea",
      "cultivar": "Torch",
      "displayName": "Panicle hydrangea 'Torch'",
      "height": "3\u20135 ft",
      "width": "3\u20134 ft",
      "heightFt": 4.0,
      "heightMinFt": 3.0,
      "heightMaxFt": 5.0,
      "widthFt": 3.5,
      "color": "Early blooming white to deep pink panicles",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "shrubs-fothergilla-mount-airy",
      "category": "Shrubs",
      "genus": "Fothergilla",
      "cultivar": "Mount Airy",
      "displayName": "Fothergilla 'Mount Airy'",
      "height": "3\u20135 ft",
      "width": "3\u20134 ft",
      "heightFt": 4.0,
      "heightMinFt": 3.0,
      "heightMaxFt": 5.0,
      "widthFt": 3.5,
      "color": "Honey-scented white brush flowers, brilliant yellow-orange fall color",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "shrubs-virginia-sweetspire-henry-s-garnet",
      "category": "Shrubs",
      "genus": "Virginia sweetspire",
      "cultivar": "Henry's Garnet",
      "displayName": "Virginia sweetspire 'Henry's Garnet'",
      "height": "3\u20135 ft",
      "width": "4\u20136 ft",
      "heightFt": 4.0,
      "heightMinFt": 3.0,
      "heightMaxFt": 5.0,
      "widthFt": 5.0,
      "color": "Fragrant white bottle-brush flowers, garnet fall color",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "4\u20135 ft"
    },
    {
      "id": "shrubs-fothergilla-legend-of-the-fall",
      "category": "Shrubs",
      "genus": "Fothergilla",
      "cultivar": "Legend of the Fall",
      "displayName": "Fothergilla 'Legend of the Fall'",
      "height": "4\u20135 ft",
      "width": "4\u20135 ft",
      "heightFt": 4.5,
      "heightMinFt": 4.0,
      "heightMaxFt": 5.0,
      "widthFt": 4.5,
      "color": "White bottle-brush flowers, vibrant multi-colored fall foliage",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "4\u20135 ft"
    },
    {
      "id": "shrubs-fothergilla-blue-shadow",
      "category": "Shrubs",
      "genus": "Fothergilla",
      "cultivar": "Blue Shadow",
      "displayName": "Fothergilla 'Blue Shadow'",
      "height": "4\u20135 ft",
      "width": "4\u20135 ft",
      "heightFt": 4.5,
      "heightMinFt": 4.0,
      "heightMaxFt": 5.0,
      "widthFt": 4.5,
      "color": "White flowers, powdery blue summer foliage & fiery fall color",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "4\u20135 ft"
    },
    {
      "id": "shrubs-ninebark-autumn-jubilee",
      "category": "Shrubs",
      "genus": "Ninebark",
      "cultivar": "Autumn Jubilee",
      "displayName": "Ninebark 'Autumn Jubilee'",
      "height": "5\u20136 ft",
      "width": "4\u20135 ft",
      "heightFt": 5.5,
      "heightMinFt": 5.0,
      "heightMaxFt": 6.0,
      "widthFt": 4.5,
      "color": "White flowers, golden-orange/purple fall foliage",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "4\u20135 ft"
    },
    {
      "id": "shrubs-ninebark-summer-wine",
      "category": "Shrubs",
      "genus": "Ninebark",
      "cultivar": "Summer Wine",
      "displayName": "Ninebark 'Summer Wine'",
      "height": "5\u20136 ft",
      "width": "5\u20136 ft",
      "heightFt": 5.5,
      "heightMinFt": 5.0,
      "heightMaxFt": 6.0,
      "widthFt": 5.5,
      "color": "Pinkish-white flowers, dark purple foliage",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "5\u20136 ft"
    },
    {
      "id": "shrubs-chokeberry-brilliantissima",
      "category": "Shrubs",
      "genus": "Chokeberry",
      "cultivar": "Brilliantissima",
      "displayName": "Chokeberry 'Brilliantissima'",
      "height": "6\u20138 ft",
      "width": "6\u20138 ft",
      "heightFt": 7.0,
      "heightMinFt": 6.0,
      "heightMaxFt": 8.0,
      "widthFt": 7.0,
      "color": "White flowers, red berries & fiery red fall foliage",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "6\u20138 ft"
    },
    {
      "id": "shrubs-panicle-hydrangea-limelight",
      "category": "Shrubs",
      "genus": "Panicle hydrangea",
      "cultivar": "Limelight",
      "displayName": "Panicle hydrangea 'Limelight'",
      "height": "6\u20138 ft",
      "width": "6\u20138 ft",
      "heightFt": 7.0,
      "heightMinFt": 6.0,
      "heightMaxFt": 8.0,
      "widthFt": 7.0,
      "color": "Lime green fading to white & pink blooms",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "6\u20138 ft"
    },
    {
      "id": "shrubs-panicle-hydrangea-quick-fire",
      "category": "Shrubs",
      "genus": "Panicle hydrangea",
      "cultivar": "Quick Fire",
      "displayName": "Panicle hydrangea 'Quick Fire'",
      "height": "6\u20138 ft",
      "width": "6\u20138 ft",
      "heightFt": 7.0,
      "heightMinFt": 6.0,
      "heightMaxFt": 8.0,
      "widthFt": 7.0,
      "color": "White flowers aging quickly to deep rose-pink",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "6\u20138 ft"
    },
    {
      "id": "shrubs-american-hazelnut-corylus-americana-straight-species",
      "category": "Shrubs",
      "genus": "American hazelnut",
      "cultivar": "Corylus americana (straight species)",
      "displayName": "American hazelnut 'Corylus americana (straight species)'",
      "height": "8\u201312 ft",
      "width": "8\u201310 ft",
      "heightFt": 10.0,
      "heightMinFt": 8.0,
      "heightMaxFt": 12.0,
      "widthFt": 9.0,
      "color": "Yellow catkins, edible hazelnuts, orange/purple fall color",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "8\u201310 ft"
    },
    {
      "id": "trees-mugo-pine-jakobsen",
      "category": "Trees",
      "genus": "Mugo Pine",
      "cultivar": "Jakobsen",
      "displayName": "Mugo Pine 'Jakobsen'",
      "height": "1\u20132 ft",
      "width": "2\u20133 ft",
      "heightFt": 1.5,
      "heightMinFt": 1.0,
      "heightMaxFt": 2.0,
      "widthFt": 2.5,
      "color": "Dark green needles, bonsai-like habit",
      "bloomTime": "",
      "seasons": [],
      "spacing": "2\u20133 ft"
    },
    {
      "id": "trees-juniper-wichita-blue",
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Wichita Blue",
      "displayName": "Juniper 'Wichita Blue'",
      "height": "10\u201315 ft",
      "width": "4\u20136 ft",
      "heightFt": 12.5,
      "heightMinFt": 10.0,
      "heightMaxFt": 15.0,
      "widthFt": 5.0,
      "color": "Bright sky-blue foliage, upright pyramidal",
      "bloomTime": "",
      "seasons": [],
      "spacing": "5\u20136 ft"
    },
    {
      "id": "trees-korean-fir-silberlocke",
      "category": "Trees",
      "genus": "Korean Fir",
      "cultivar": "Silberlocke",
      "displayName": "Korean Fir 'Silberlocke'",
      "height": "10\u201315 ft",
      "width": "6\u20138 ft",
      "heightFt": 12.5,
      "heightMinFt": 10.0,
      "heightMaxFt": 15.0,
      "widthFt": 7.0,
      "color": "Curled green needles showing silver undersides",
      "bloomTime": "",
      "seasons": [],
      "spacing": "6\u20138 ft"
    },
    {
      "id": "trees-juniper-gin-fizz",
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Gin Fizz",
      "displayName": "Juniper 'Gin Fizz'",
      "height": "10\u201318 ft",
      "width": "7\u201310 ft",
      "heightFt": 14.0,
      "heightMinFt": 10.0,
      "heightMaxFt": 18.0,
      "widthFt": 8.5,
      "color": "Blue-green foliage, heavy blue berries",
      "bloomTime": "",
      "seasons": [],
      "spacing": "6\u20138 ft"
    },
    {
      "id": "trees-serviceberry-standing-ovation",
      "category": "Trees",
      "genus": "Serviceberry",
      "cultivar": "Standing Ovation",
      "displayName": "Serviceberry 'Standing Ovation'",
      "height": "12\u201315 ft",
      "width": "3\u20134 ft",
      "heightFt": 13.5,
      "heightMinFt": 12.0,
      "heightMaxFt": 15.0,
      "widthFt": 3.5,
      "color": "White flowers, red/dark berries",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "4\u20136 ft"
    },
    {
      "id": "trees-bosnian-pine-emerald-arrow",
      "category": "Trees",
      "genus": "Bosnian Pine",
      "cultivar": "Emerald Arrow",
      "displayName": "Bosnian Pine 'Emerald Arrow'",
      "height": "12\u201315 ft",
      "width": "4\u20136 ft",
      "heightFt": 13.5,
      "heightMinFt": 12.0,
      "heightMaxFt": 15.0,
      "widthFt": 5.0,
      "color": "Deep emerald green needles, columnar",
      "bloomTime": "",
      "seasons": [],
      "spacing": "5\u20136 ft"
    },
    {
      "id": "trees-juniper-torulosa",
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Torulosa",
      "displayName": "Juniper 'Torulosa'",
      "height": "12\u201315 ft",
      "width": "6\u20138 ft",
      "heightFt": 13.5,
      "heightMinFt": 12.0,
      "heightMaxFt": 15.0,
      "widthFt": 7.0,
      "color": "Rich green twisted foliage, sculptural habit",
      "bloomTime": "",
      "seasons": [],
      "spacing": "6\u20138 ft"
    },
    {
      "id": "trees-eastern-redbud-black-pearl",
      "category": "Trees",
      "genus": "Eastern redbud",
      "cultivar": "Black Pearl",
      "displayName": "Eastern redbud 'Black Pearl'",
      "height": "15\u201320 ft",
      "width": "15\u201320 ft",
      "heightFt": 17.5,
      "heightMinFt": 15.0,
      "heightMaxFt": 20.0,
      "widthFt": 17.5,
      "color": "Lavender-pink, dark purple/black foliage",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "15\u201320 ft"
    },
    {
      "id": "trees-serviceberry-rainbow-pillar",
      "category": "Trees",
      "genus": "Serviceberry",
      "cultivar": "Rainbow Pillar",
      "displayName": "Serviceberry 'Rainbow Pillar'",
      "height": "15\u201320 ft",
      "width": "8\u201310 ft",
      "heightFt": 17.5,
      "heightMinFt": 15.0,
      "heightMaxFt": 20.0,
      "widthFt": 9.0,
      "color": "White flowers, dark purple berries",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "8\u201310 ft"
    },
    {
      "id": "trees-eastern-redbud-appalachian-red",
      "category": "Trees",
      "genus": "Eastern redbud",
      "cultivar": "Appalachian Red",
      "displayName": "Eastern redbud 'Appalachian Red'",
      "height": "15\u201325 ft",
      "width": "15\u201325 ft",
      "heightFt": 20.0,
      "heightMinFt": 15.0,
      "heightMaxFt": 25.0,
      "widthFt": 20.0,
      "color": "Fuchsia/bright pink-red flowers",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "15\u201320 ft"
    },
    {
      "id": "trees-mugo-pine-blue-shag",
      "category": "Trees",
      "genus": "Mugo Pine",
      "cultivar": "Blue Shag",
      "displayName": "Mugo Pine 'Blue Shag'",
      "height": "2\u20134 ft",
      "width": "2\u20134 ft",
      "heightFt": 3.0,
      "heightMinFt": 2.0,
      "heightMaxFt": 4.0,
      "widthFt": 3.0,
      "color": "Soft blue-green needles, mounding",
      "bloomTime": "",
      "seasons": [],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "trees-serviceberry-autumn-brilliance",
      "category": "Trees",
      "genus": "Serviceberry",
      "cultivar": "Autumn Brilliance",
      "displayName": "Serviceberry 'Autumn Brilliance'",
      "height": "20\u201325 ft",
      "width": "15\u201320 ft",
      "heightFt": 22.5,
      "heightMinFt": 20.0,
      "heightMaxFt": 25.0,
      "widthFt": 17.5,
      "color": "White flowers, orange-red fall foliage",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "15\u201320 ft"
    },
    {
      "id": "trees-japanese-tree-lilac-ivory-silk",
      "category": "Trees",
      "genus": "Japanese tree lilac",
      "cultivar": "Ivory Silk",
      "displayName": "Japanese tree lilac 'Ivory Silk'",
      "height": "20\u201325 ft",
      "width": "15\u201320 ft",
      "heightFt": 22.5,
      "heightMinFt": 20.0,
      "heightMaxFt": 25.0,
      "widthFt": 17.5,
      "color": "Creamy white fragrant flowers",
      "bloomTime": "Early Summer",
      "seasons": [
        "Early Summer"
      ],
      "spacing": "15\u201320 ft"
    },
    {
      "id": "trees-eastern-white-pine-golden-candles",
      "category": "Trees",
      "genus": "Eastern white pine",
      "cultivar": "Golden Candles",
      "displayName": "Eastern white pine 'Golden Candles'",
      "height": "20\u201330 ft",
      "width": "10\u201315 ft",
      "heightFt": 25.0,
      "heightMinFt": 20.0,
      "heightMaxFt": 30.0,
      "widthFt": 12.5,
      "color": "Golden yellow needle tips, evergreen",
      "bloomTime": "",
      "seasons": [],
      "spacing": "12\u201315 ft"
    },
    {
      "id": "trees-mugo-pine-green-candle",
      "category": "Trees",
      "genus": "Mugo Pine",
      "cultivar": "Green Candle",
      "displayName": "Mugo Pine 'Green Candle'",
      "height": "3\u20135 ft",
      "width": "3\u20134 ft",
      "heightFt": 4.0,
      "heightMinFt": 3.0,
      "heightMaxFt": 5.0,
      "widthFt": 3.5,
      "color": "Rich green needles with showy white candles",
      "bloomTime": "",
      "seasons": [],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "trees-juniper-mint-julep",
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Mint Julep",
      "displayName": "Juniper 'Mint Julep'",
      "height": "3\u20135 ft",
      "width": "4\u20136 ft",
      "heightFt": 4.0,
      "heightMinFt": 3.0,
      "heightMaxFt": 5.0,
      "widthFt": 5.0,
      "color": "Mint-green foliage, arching branches",
      "bloomTime": "",
      "seasons": [],
      "spacing": "4\u20135 ft"
    },
    {
      "id": "trees-eastern-red-cedar-straight-species",
      "category": "Trees",
      "genus": "Eastern red cedar",
      "cultivar": "Straight species",
      "displayName": "Eastern red cedar",
      "height": "30\u201340 ft",
      "width": "8\u201315 ft",
      "heightFt": 35.0,
      "heightMinFt": 30.0,
      "heightMaxFt": 40.0,
      "widthFt": 11.5,
      "color": "Dark green/bronze evergreen, blue cones",
      "bloomTime": "",
      "seasons": [],
      "spacing": "10\u201315 ft"
    },
    {
      "id": "trees-eastern-white-pine-mini-twists",
      "category": "Trees",
      "genus": "Eastern white pine",
      "cultivar": "Mini Twists",
      "displayName": "Eastern white pine 'Mini Twists'",
      "height": "4\u20136 ft",
      "width": "3\u20134 ft",
      "heightFt": 5.0,
      "heightMinFt": 4.0,
      "heightMaxFt": 6.0,
      "widthFt": 3.5,
      "color": "Twisted blue-green needles",
      "bloomTime": "",
      "seasons": [],
      "spacing": "4\u20135 ft"
    },
    {
      "id": "trees-red-maple-redpointe",
      "category": "Trees",
      "genus": "Red maple",
      "cultivar": "Redpointe",
      "displayName": "Red maple 'Redpointe'",
      "height": "40\u201345 ft",
      "width": "25\u201330 ft",
      "heightFt": 42.5,
      "heightMinFt": 40.0,
      "heightMaxFt": 45.0,
      "widthFt": 27.5,
      "color": "Red flowers, bright red fall color",
      "bloomTime": "Fall",
      "seasons": [
        "Fall"
      ],
      "spacing": "20\u201325 ft"
    },
    {
      "id": "trees-red-maple-october-glory",
      "category": "Trees",
      "genus": "Red maple",
      "cultivar": "October Glory",
      "displayName": "Red maple 'October Glory'",
      "height": "40\u201350 ft",
      "width": "30\u201340 ft",
      "heightFt": 45.0,
      "heightMinFt": 40.0,
      "heightMaxFt": 50.0,
      "widthFt": 35.0,
      "color": "Red flowers, deep crimson fall foliage",
      "bloomTime": "Fall",
      "seasons": [
        "Fall"
      ],
      "spacing": "25\u201330 ft"
    },
    {
      "id": "trees-river-birch-heritage",
      "category": "Trees",
      "genus": "River birch",
      "cultivar": "Heritage",
      "displayName": "River birch 'Heritage'",
      "height": "40\u201350 ft",
      "width": "30\u201340 ft",
      "heightFt": 45.0,
      "heightMinFt": 40.0,
      "heightMaxFt": 50.0,
      "widthFt": 35.0,
      "color": "Exfoliating creamy salmon bark",
      "bloomTime": "",
      "seasons": [],
      "spacing": "25\u201330 ft"
    },
    {
      "id": "trees-red-maple-red-sunset",
      "category": "Trees",
      "genus": "Red maple",
      "cultivar": "Red Sunset",
      "displayName": "Red maple 'Red Sunset'",
      "height": "45\u201350 ft",
      "width": "35\u201340 ft",
      "heightFt": 47.5,
      "heightMinFt": 45.0,
      "heightMaxFt": 50.0,
      "widthFt": 37.5,
      "color": "Red flowers, brilliant red fall foliage",
      "bloomTime": "Fall",
      "seasons": [
        "Fall"
      ],
      "spacing": "25\u201330 ft"
    },
    {
      "id": "trees-white-oak-straight-species",
      "category": "Trees",
      "genus": "White oak",
      "cultivar": "Straight species",
      "displayName": "White oak",
      "height": "50\u201380 ft",
      "width": "50\u201380 ft",
      "heightFt": 65.0,
      "heightMinFt": 50.0,
      "heightMaxFt": 80.0,
      "widthFt": 65.0,
      "color": "Inconspicuous blooms, red/wine fall color",
      "bloomTime": "Fall",
      "seasons": [
        "Fall"
      ],
      "spacing": "30\u201340 ft"
    },
    {
      "id": "trees-red-oak-straight-species",
      "category": "Trees",
      "genus": "Red oak",
      "cultivar": "Straight species",
      "displayName": "Red oak",
      "height": "60\u201375 ft",
      "width": "45\u201350 ft",
      "heightFt": 67.5,
      "heightMinFt": 60.0,
      "heightMaxFt": 75.0,
      "widthFt": 47.5,
      "color": "Inconspicuous blooms, bright red fall foliage",
      "bloomTime": "Fall",
      "seasons": [
        "Fall"
      ],
      "spacing": "30\u201340 ft"
    },
    {
      "id": "trees-tulip-tree-liriodendron-tulipifera",
      "category": "Trees",
      "genus": "Tulip tree",
      "cultivar": "Liriodendron tulipifera",
      "displayName": "Tulip tree 'Liriodendron tulipifera'",
      "height": "70\u201390 ft",
      "width": "35\u201350 ft",
      "heightFt": 80.0,
      "heightMinFt": 70.0,
      "heightMaxFt": 90.0,
      "widthFt": 42.5,
      "color": "Tulip-shaped yellow-green & orange flowers",
      "bloomTime": "Spring",
      "seasons": [
        "Spring"
      ],
      "spacing": "35\u201340 ft"
    },
    {
      "id": "trees-eastern-white-pine-stowe-s-pillar",
      "category": "Trees",
      "genus": "Eastern white pine",
      "cultivar": "Stowe's Pillar",
      "displayName": "Eastern white pine 'Stowe's Pillar'",
      "height": "8\u201310 ft",
      "width": "2\u20133 ft",
      "heightFt": 9.0,
      "heightMinFt": 8.0,
      "heightMaxFt": 10.0,
      "widthFt": 2.5,
      "color": "Blue-green needles, columnar foliage",
      "bloomTime": "",
      "seasons": [],
      "spacing": "3\u20134 ft"
    },
    {
      "id": "trees-spruce-serbian-spruce-nana",
      "category": "Trees",
      "genus": "Spruce",
      "cultivar": "Serbian spruce 'Nana'",
      "displayName": "Spruce 'Serbian spruce 'Nana''",
      "height": "8\u201310 ft",
      "width": "8\u201310 ft",
      "heightFt": 9.0,
      "heightMinFt": 8.0,
      "heightMaxFt": 10.0,
      "widthFt": 9.0,
      "color": "Blue-green and silver needles, dwarf cone",
      "bloomTime": "",
      "seasons": [],
      "spacing": "8\u201310 ft"
    },
    {
      "id": "trees-juniper-green-columnar",
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Green Columnar",
      "displayName": "Juniper 'Green Columnar'",
      "height": "15 ft",
      "width": "5 ft",
      "heightFt": 15.0,
      "heightMinFt": 15.0,
      "heightMaxFt": 15.0,
      "widthFt": 5.0,
      "color": "",
      "bloomTime": "",
      "seasons": [],
      "spacing": "5 ft"
    },
    {
      "id": "trees-juniper-hollywood",
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Hollywood",
      "displayName": "Juniper 'Hollywood'",
      "height": "15 ft",
      "width": "10 ft",
      "heightFt": 15.0,
      "heightMinFt": 15.0,
      "heightMaxFt": 15.0,
      "widthFt": 10.0,
      "color": "",
      "bloomTime": "",
      "seasons": [],
      "spacing": ""
    },
    {
      "id": "trees-juniper-pfitzeriana-aurea-improved",
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "pfitzeriana 'Aurea Improved'",
      "displayName": "Juniper 'pfitzeriana 'Aurea Improved''",
      "height": "3 ft",
      "width": "4 ft",
      "heightFt": 3.0,
      "heightMinFt": 3.0,
      "heightMaxFt": 3.0,
      "widthFt": 4.0,
      "color": "",
      "bloomTime": "",
      "seasons": [],
      "spacing": ""
    },
    {
      "id": "trees-juniper-bluepoint",
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Bluepoint",
      "displayName": "Juniper 'Bluepoint'",
      "height": "12 ft",
      "width": "8 ft",
      "heightFt": 12.0,
      "heightMinFt": 12.0,
      "heightMaxFt": 12.0,
      "widthFt": 8.0,
      "color": "",
      "bloomTime": "",
      "seasons": [],
      "spacing": ""
    },
    {
      "id": "trees-juniper-skyrocket",
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Skyrocket",
      "displayName": "Juniper 'Skyrocket'",
      "height": "15-20 ft",
      "width": "2-3 ft",
      "heightFt": 17.5,
      "heightMinFt": 15.0,
      "heightMaxFt": 20.0,
      "widthFt": 2.5,
      "color": "",
      "bloomTime": "",
      "seasons": [],
      "spacing": ""
    },
    {
      "id": "trees-juniper-moonglow",
      "category": "Trees",
      "genus": "Juniper",
      "cultivar": "Moonglow",
      "displayName": "Juniper 'Moonglow'",
      "height": "20 ft",
      "width": "8 ft",
      "heightFt": 20.0,
      "heightMinFt": 20.0,
      "heightMaxFt": 20.0,
      "widthFt": 8.0,
      "color": "",
      "bloomTime": "",
      "seasons": [],
      "spacing": ""
    },
    {
      "id": "vines-clematis-virginiana",
      "category": "Vines",
      "genus": "Clematis",
      "cultivar": "Virginiana",
      "displayName": "Clematis 'Virginiana'",
      "height": "12\u201320 ft",
      "width": "1 ft",
      "heightFt": 16.0,
      "heightMinFt": 12.0,
      "heightMaxFt": 20.0,
      "widthFt": 1.0,
      "color": "Fragrant white starry flower clusters, feathery seed heads",
      "bloomTime": "Late Summer",
      "seasons": [
        "Late Summer"
      ],
      "spacing": "4\u20136 ft"
    },
    {
      "id": "vines-grapes-somerset-seedless",
      "category": "Vines",
      "genus": "Grapes",
      "cultivar": "Somerset Seedless",
      "displayName": "Grapes 'Somerset Seedless'",
      "height": "15\u201320 ft",
      "width": "1 ft",
      "heightFt": 17.5,
      "heightMinFt": 15.0,
      "heightMaxFt": 20.0,
      "widthFt": 1.0,
      "color": "Inconspicuous blooms, sweet strawberry-flavored red grapes",
      "bloomTime": "",
      "seasons": [],
      "spacing": "8\u201310 ft"
    },
    {
      "id": "vines-grapes-candice",
      "category": "Vines",
      "genus": "Grapes",
      "cultivar": "Candice",
      "displayName": "Grapes 'Candice'",
      "height": "15\u201320 ft",
      "width": "1 ft",
      "heightFt": 17.5,
      "heightMinFt": 15.0,
      "heightMaxFt": 20.0,
      "widthFt": 1.0,
      "color": "Inconspicuous blooms, sweet red seedless grapes",
      "bloomTime": "",
      "seasons": [],
      "spacing": "8\u201310 ft"
    }
  ]
};
